# Generated by Django 4.2.7 on 2025-07-01 11:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                (
                    "preferred_auth_method",
                    models.CharField(
                        choices=[("passkey", "Passkey"), ("email", "Email Magic Link")],
                        default="passkey",
                        max_length=20,
                        verbose_name="Preferred Authentication Method",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "has_passkey",
                    models.BooleanField(default=False, verbose_name="Has Passkey"),
                ),
                (
                    "has_2fa",
                    models.BooleanField(default=False, verbose_name="Has 2FA Enabled"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_login_method",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Last Login Method"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=255, verbose_name="Device Name"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web Browser"),
                            ("desktop", "Desktop"),
                        ],
                        max_length=20,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Device ID"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.TextField(blank=True, verbose_name="Device Fingerprint"),
                ),
                (
                    "supports_passkey",
                    models.BooleanField(default=False, verbose_name="Supports Passkey"),
                ),
                (
                    "supports_biometric",
                    models.BooleanField(
                        default=False, verbose_name="Supports Biometric"
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(default=False, verbose_name="Is Trusted"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "trust_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trust Expires At"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="Last Used"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Device",
                "verbose_name_plural": "User Devices",
            },
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="Recovery Code"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery Code",
                "verbose_name_plural": "Recovery Codes",
            },
        ),
        migrations.CreateModel(
            name="EmailMagicLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Magic Link Token"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("signup", "Signup Verification"),
                            ("recovery", "Account Recovery"),
                        ],
                        max_length=20,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Requesting IP Address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Magic Link",
                "verbose_name_plural": "Email Magic Links",
            },
        ),
        migrations.CreateModel(
            name="CrossDeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Session ID"
                    ),
                ),
                (
                    "requesting_device",
                    models.JSONField(verbose_name="Requesting Device Info"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "approving_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userdevice",
                        verbose_name="Approving Device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cross-Device Session",
                "verbose_name_plural": "Cross-Device Sessions",
            },
        ),
        migrations.CreateModel(
            name="AuthenticationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("passkey", "Passkey"),
                            ("email_magic_link", "Email Magic Link"),
                            ("email_code", "Email Code"),
                            ("totp", "TOTP"),
                            ("recovery_code", "Recovery Code"),
                            ("cross_device", "Cross-Device"),
                        ],
                        max_length=20,
                        verbose_name="Authentication Method",
                    ),
                ),
                ("success", models.BooleanField(verbose_name="Success")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Failure Reason"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="Device Info"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Log",
                "verbose_name_plural": "Authentication Logs",
            },
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_active"], name="authenticat_user_id_7df9d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["device_id"], name="authenticat_device__80a4c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["last_used"], name="authenticat_last_us_43ce04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoverycode",
            index=models.Index(
                fields=["user", "used_at"], name="authenticat_user_id_2bd5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoverycode",
            index=models.Index(fields=["code"], name="authenticat_code_8bd01f_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmagiclink",
            index=models.Index(fields=["token"], name="authenticat_token_c17505_idx"),
        ),
        migrations.AddIndex(
            model_name="emailmagiclink",
            index=models.Index(
                fields=["user", "purpose"], name="authenticat_user_id_1ae029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailmagiclink",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_b8a9f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdevicesession",
            index=models.Index(
                fields=["session_id"], name="authenticat_session_1b9f65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdevicesession",
            index=models.Index(
                fields=["user", "status"], name="authenticat_user_id_56663e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossdevicesession",
            index=models.Index(
                fields=["expires_at"], name="authenticat_expires_795561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationlog",
            index=models.Index(
                fields=["user", "timestamp"], name="authenticat_user_id_513dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationlog",
            index=models.Index(
                fields=["method", "success"], name="authenticat_method_c6105f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authenticationlog",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="authenticat_ip_addr_f7d335_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="authenticat_email_d74434_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="authenticat_created_b28532_idx"
            ),
        ),
    ]
