# Generated by Django 4.2.7 on 2025-07-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(unique=True, verbose_name="Credential ID"),
                ),
                ("public_key_pem", models.TextField(verbose_name="Public Key PEM")),
                (
                    "sign_count",
                    models.IntegerField(default=0, verbose_name="Sign Count"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform Authenticator"),
                            ("security_key", "Security Key"),
                        ],
                        max_length=20,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Device Name",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey Credential",
                "verbose_name_plural": "Passkey Credentials",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Session Token"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Device Fingerprint",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="Last Activity"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.passkeycredential",
                        verbose_name="Passkey Credential",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "indexes": [
                    models.Index(
                        fields=["user"], name="authenticat_user_id_43ea0f_idx"
                    ),
                    models.Index(
                        fields=["session_token"], name="authenticat_session_30c7e0_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_8c23d2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="authenticat_is_acti_46022b_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(fields=["user"], name="authenticat_user_id_add09e_idx"),
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(
                fields=["credential_id"], name="authenticat_credent_2a6b0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passkeycredential",
            index=models.Index(
                fields=["is_active"], name="authenticat_is_acti_56d8b6_idx"
            ),
        ),
    ]
