# Generated by Django 4.2.23 on 2025-07-16 15:23

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_passkeycredential_usersession_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="emailmagiclink",
            name="firebase_link",
            field=models.URLField(blank=True, verbose_name="Firebase Generated Link"),
        ),
        migrations.AddField(
            model_name="emailmagiclink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom Token"),
                    ("firebase", "Firebase Generated"),
                ],
                default="custom",
                max_length=20,
                verbose_name="Link Type",
            ),
        ),
        migrations.AddIndex(
            model_name="emailmagiclink",
            index=models.Index(
                fields=["link_type"], name="authenticat_link_ty_b75d7b_idx"
            ),
        ),
    ]
