# Generated by Django 4.2.23 on 2025-07-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_alter_user_managers_emailmagiclink_firebase_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                help_text="Firebase user ID for cross-platform authentication",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
