# Generated by Django 4.2.7 on 2025-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_firebase_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmagiclink",
            name="firebase_link",
            field=models.TextField(blank=True, verbose_name="Firebase Generated Link"),
        ),
    ]
