# Generated by Django 4.2.7 on 2025-07-27 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_emailmagiclink_firebase_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "code",
                    models.CharField(max_length=6, verbose_name="Verification Code"),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "Signup"),
                            ("signin", "Sign In"),
                            ("recovery", "Account Recovery"),
                        ],
                        max_length=20,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, verbose_name="Failed Attempts"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Requesting IP Address"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Verification Code",
                "verbose_name_plural": "Email Verification Codes",
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "created_at"],
                        name="authenticat_email_32886a_idx",
                    ),
                    models.Index(
                        fields=["code", "email"], name="authenticat_code_b9eb4f_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_1c4fd8_idx"
                    ),
                    models.Index(
                        fields=["user", "purpose"],
                        name="authenticat_user_id_1378d9_idx",
                    ),
                ],
            },
        ),
    ]
