# Generated by Django 4.2.7 on 2025-10-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_fix_authlog_method_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authenticationlog",
            name="method",
            field=models.CharField(
                choices=[
                    ("passkey", "Passkey"),
                    ("email_magic_link", "Email Magic Link"),
                    ("email_code", "Email Code"),
                    ("totp", "TOTP"),
                    ("recovery_code", "Recovery Code"),
                    ("cross_device", "Cross-Device"),
                ],
                max_length=20,
                verbose_name="Authentication Method",
            ),
        ),
    ]
