# Generated by Django 4.2.7 on 2025-12-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_alter_authenticationlog_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Verification Attempts"
            ),
        ),
    ]
