# Generated by Django 4.2.7 on 2025-12-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_add_attempts_to_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="device_token",
            field=models.CharField(
                blank=True,
                help_text="FCM/APNs device token for push notifications",
                max_length=512,
                null=True,
                verbose_name="Push Token",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="push_enabled",
            field=models.BooleanField(
                default=True,
                help_text="User can disable push notifications for this specific device",
                verbose_name="Push Enabled",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of device token for DuckLake storage (PII protection)",
                max_length=64,
                null=True,
                verbose_name="Token Hash",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="token_type",
            field=models.CharField(
                blank=True,
                choices=[("fcm", "FCM"), ("apns", "APNs")],
                help_text="Push notification provider type",
                max_length=10,
                null=True,
                verbose_name="Token Type",
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="token_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when device token was last updated",
                null=True,
                verbose_name="Token Updated At",
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "push_enabled"], name="authenticat_user_id_b6599d_idx"
            ),
        ),
    ]
