input:
  websocket:
    url: ${AVAX_WEBSOCKET_URL} 
    open_message: '{
        "jsonrpc":"2.0",
        "method":"eth_subscribe",
        "params":["newHeads"],
        "id":1
    }'

pipeline:
  processors:
    - log:
        level: INFO
        message: "Received message: ${!content()}"


output:
  broker:
    pattern: fan_out
    outputs:
      - redis_pubsub:
          url: "redis://redis:6379"
          channel: "eth_get_transactions"
      - aws_s3:
          bucket: ${MINIO_BUCKET}
          endpoint: "http://minio:9000"
          credentials:
            id: ${MINIO_ACCESS_KEY}
            secret: ${MINIO_SECRET_KEY}
          region: us-east-1
          path: "${!timestamp_unix()}_${!uuid_v4()}.json"
          force_path_style_urls: true



