version: '3'

services:
  bento:
    build: .
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - bento-network
    depends_on:
      - redis
      - minio

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - bento-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - bento-network

volumes:
  minio_data:

networks:
  bento-network:
    driver: bridge
