version: '3'

services:
  streamlit:
    build:
      context: ./streamlit/ekko-dash
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./streamlit/ekko-dash:/app
    ports:
      - "8501:8501"
    networks:
      - pipeline-network
    depends_on:
      - valkey
      - pulsar
