version: '3'

services:
  streamlit:
    build:
      context: ./streamlit/ekko-dash
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - BENTO_API_URL=http://bento:8000
    volumes:
      - ./streamlit/ekko-dash:/app
      - duckdb_data:/data
    ports:
      - "8501:8501"
    networks:
      - bento-network
    depends_on:
      - redis
      - minio
      - bento
