# Generated by Django 4.2.7 on 2025-07-01 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("chain_type", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blockchain",
                "verbose_name_plural": "Blockchains",
                "db_table": "blockchain",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Dao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DAO",
                "verbose_name_plural": "DAOs",
                "db_table": "dao",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("url", models.URLField(blank=True, max_length=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "db_table": "story",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("name", models.TextField()),
                (
                    "derived_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("domains", models.JSONField(blank=True, null=True)),
                ("recommended", models.BooleanField(default=False)),
                ("balance", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("subnet", models.CharField(default="mainnet", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blockchain",
                    models.ForeignKey(
                        db_column="blockchain_symbol",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="blockchain.blockchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallet",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blockchain",
                    models.ForeignKey(
                        db_column="blockchain_symbol",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="blockchain.blockchain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "db_table": "token",
            },
        ),
        migrations.CreateModel(
            name="DaoWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dao_wallets",
                        to="blockchain.dao",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dao_wallets",
                        to="blockchain.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "DAO Wallet",
                "verbose_name_plural": "DAO Wallets",
                "db_table": "daoWallet",
            },
        ),
        migrations.CreateModel(
            name="DaoSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("notifications_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="blockchain.dao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dao_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DAO Subscription",
                "verbose_name_plural": "DAO Subscriptions",
                "db_table": "daoSubscription",
            },
        ),
        migrations.CreateModel(
            name="BlockchainStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blockchain",
                    models.ForeignKey(
                        db_column="blockchain_symbol",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.blockchain",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_stories",
                        to="blockchain.story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blockchain Story",
                "verbose_name_plural": "Blockchain Stories",
                "db_table": "story_blockchain",
            },
        ),
        migrations.CreateModel(
            name="WalletSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("notifications_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="blockchain.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Subscription",
                "verbose_name_plural": "Wallet Subscriptions",
                "db_table": "walletSubscription",
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="walletSubsc_wallet__dc9ed8_idx"
                    ),
                    models.Index(
                        fields=["user"], name="walletSubsc_user_id_cfc4b5_idx"
                    ),
                ],
                "unique_together": {("wallet", "user")},
            },
        ),
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("balance", models.CharField(max_length=255)),
                (
                    "token_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fiat_value", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="blockchain.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Balance",
                "verbose_name_plural": "Wallet Balances",
                "db_table": "wallet_balances",
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="wallet_bala_wallet__cf9694_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="wallet_bala_timesta_6e6f25_idx"
                    ),
                    models.Index(
                        fields=["wallet", "timestamp"],
                        name="wallet_bala_wallet__303aa3_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["blockchain"], name="wallet_blockch_09e8e5_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["address"], name="wallet_address_7130a3_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["recommended"], name="wallet_recomme_046017_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("blockchain", "address")},
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["blockchain"], name="token_blockch_5f1d4f_idx"),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["symbol"], name="token_symbol_216dd2_idx"),
        ),
        migrations.AddIndex(
            model_name="daowallet",
            index=models.Index(fields=["dao"], name="daoWallet_dao_id_1c0c73_idx"),
        ),
        migrations.AddIndex(
            model_name="daowallet",
            index=models.Index(fields=["wallet"], name="daoWallet_wallet__afea8c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="daowallet",
            unique_together={("dao", "wallet")},
        ),
        migrations.AddIndex(
            model_name="daosubscription",
            index=models.Index(fields=["dao"], name="daoSubscrip_dao_id_0e0276_idx"),
        ),
        migrations.AddIndex(
            model_name="daosubscription",
            index=models.Index(fields=["user"], name="daoSubscrip_user_id_e79f6c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="daosubscription",
            unique_together={("dao", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="blockchainstory",
            unique_together={("story", "blockchain")},
        ),
    ]
