# Generated by Django 4.2.23 on 2025-07-16 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("chain_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("rpc_url", models.URLField(blank=True, max_length=500)),
                ("explorer_url", models.URLField(blank=True, max_length=500)),
                ("native_token", models.CharField(blank=True, max_length=10)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chain",
                "verbose_name_plural": "Chains",
                "db_table": "chains",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="SubChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("network_id", models.IntegerField(blank=True, null=True)),
                ("rpc_url", models.URLField(blank=True, max_length=500)),
                ("explorer_url", models.URLField(blank=True, max_length=500)),
                ("is_testnet", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_chains",
                        to="blockchain.chain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Chain",
                "verbose_name_plural": "Sub Chains",
                "db_table": "sub_chains",
                "ordering": ["chain__display_name", "display_name"],
            },
        ),
        migrations.AddIndex(
            model_name="chain",
            index=models.Index(fields=["enabled"], name="chains_enabled_56e15d_idx"),
        ),
        migrations.AddIndex(
            model_name="chain",
            index=models.Index(fields=["name"], name="chains_name_277909_idx"),
        ),
        migrations.AddIndex(
            model_name="subchain",
            index=models.Index(
                fields=["chain", "enabled"], name="sub_chains_chain_i_a67da1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subchain",
            index=models.Index(
                fields=["is_testnet"], name="sub_chains_is_test_f1aeb3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subchain",
            unique_together={("chain", "name")},
        ),
    ]
