# Generated by Django 4.2.7 on 2025-08-11 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blockchain", "0002_chain_subchain_chain_chains_enabled_56e15d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("wallet_data", models.JSONField(blank=True, default=dict)),
                (
                    "color",
                    models.CharField(blank=True, default="#4A90E2", max_length=7),
                ),
                ("icon", models.CharField(blank=True, default="wallet", max_length=50)),
                (
                    "tags",
                    models.JSONField(blank=True, default=list),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("team", "Team"),
                            ("organization", "Organization"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_wallet_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_groups",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Group",
                "verbose_name_plural": "Wallet Groups",
                "db_table": "wallet_groups",
            },
        ),
        migrations.CreateModel(
            name="WalletImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("successful_rows", models.IntegerField(default=0)),
                ("error_rows", models.IntegerField(default=0)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("error_messages", models.JSONField(blank=True, default=list)),
                ("import_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="blockchain.walletgroup",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_import_batches",
            },
        ),
        migrations.CreateModel(
            name="WalletGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="blockchain.walletgroup",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_group_memberships",
            },
        ),
        migrations.CreateModel(
            name="WalletImportError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("error_type", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("row_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_errors",
                        to="blockchain.walletimportbatch",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_import_errors",
                "indexes": [
                    models.Index(
                        fields=["import_batch"], name="wallet_impo_import__377c05_idx"
                    ),
                    models.Index(
                        fields=["error_type"], name="wallet_impo_error_t_03c6cc_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="walletimportbatch",
            index=models.Index(
                fields=["wallet_group"], name="wallet_impo_wallet__f17aba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletimportbatch",
            index=models.Index(fields=["status"], name="wallet_impo_status_3706b4_idx"),
        ),
        migrations.AddIndex(
            model_name="walletimportbatch",
            index=models.Index(
                fields=["created_at"], name="wallet_impo_created_3c9ac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroupmembership",
            index=models.Index(
                fields=["wallet_group"], name="wallet_grou_wallet__65c129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroupmembership",
            index=models.Index(fields=["user"], name="wallet_grou_user_id_d219e9_idx"),
        ),
        migrations.AddIndex(
            model_name="walletgroupmembership",
            index=models.Index(fields=["role"], name="wallet_grou_role_24f77a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="walletgroupmembership",
            unique_together={("wallet_group", "user")},
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["created_by"], name="wallet_grou_created_9390eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["organization"], name="wallet_grou_organiz_23fda5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["is_active"], name="wallet_grou_is_acti_fa1d10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["is_template"], name="wallet_grou_is_temp_d78698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["visibility"], name="wallet_grou_visibil_1c3e09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletgroup",
            index=models.Index(
                fields=["created_at"], name="wallet_grou_created_225130_idx"
            ),
        ),
    ]
