# Generated by Django 4.2.7 on 2025-10-21 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0005_add_wallet_nicknames"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="token",
            new_name="token_chain_i_b3e34c_idx",
            old_name="token_chain__is_nat_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_chain_i_969297_idx",
            old_name="token_chain__contra_idx",
        ),
        migrations.RenameIndex(
            model_name="token",
            new_name="token_is_nati_439a35_idx",
            old_name="token_is_native_idx",
        ),
        migrations.RenameIndex(
            model_name="walletnickname",
            new_name="wallet_nick_user_id_9ee9a4_idx",
            old_name="wallet_nick_user_id_c8e1f3_idx",
        ),
        migrations.RenameIndex(
            model_name="walletnickname",
            new_name="wallet_nick_wallet__8c46f2_idx",
            old_name="wallet_nick_wallet__a72b9e_idx",
        ),
    ]
