# Generated by Django 4.2.7 on 2025-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_accesspattern_user_and_more"),
        ("blockchain", "0006_remove_token_token_blockch_5f1d4f_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WalletGroup",
        ),
        migrations.DeleteModel(
            name="WalletGroupMembership",
        ),
        migrations.DeleteModel(
            name="WalletImportBatch",
        ),
        migrations.DeleteModel(
            name="WalletImportError",
        ),
    ]
