api:
  endpoint: http://bento:8000
  key: ''
app:
  auto_refresh: true
  cache_duration: 15
  notifications_enabled: true
  refresh_interval: 60
  theme: Light
cache:
  enabled: true
  ttl: 300
database:
  host: localhost
  path: /data/ekko.db
  pool_size: 5
minio:
  access_key: minioadmin
  bucket: ekko-data
  secret_key: minioadmin
  secure: false
  url: http://localhost:9000
redis:
  db: 0
  url: redis://valkey:6379
