database:
  host: localhost  # Change this for remote database connections
  path: ekko.db
  pool_size: 5

redis:
  host: localhost  # Change this for remote Redis server
  port: 6379
  db: 0

cache:
  enabled: true
  ttl: 300  # 5 minutes

api:
  endpoint: http://bento:8000
  key: ''

app:
  theme: Light
  notifications_enabled: true
  auto_refresh: true
  cache_duration: 15
