spin_manifest_version = 2

[application]
name = "ekkoConsumer"
version = "0.1.0"
authors = ["abrahamalaka <abraham@ekko.zone>"]
description = "Wasm driven backend for the Ekko App."

[variables]
redis_url = { required = true }
eth_api_url = { required = true }

[[trigger.http]]
route = "/health"
component = "ekkoconsumer"

[component.ekkoconsumer]
source = "target/wasm32-wasi/release/ekkoconsumer.wasm"
allowed_outbound_hosts = [
    "redis://*",  
]

[component.ekkoconsumer.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.ekkoconsumer.variables]
redis_url = "{{ redis_url}}"
eth_api_url = "{{ eth_api_url }}"

[[trigger.redis]]
channel = "eth_raw_transactions"
component = "eth-raw-transactions"

[component.eth-raw-transactions]
source = "eth_raw_transactions/target/wasm32-wasi/release/eth_raw_transactions.wasm"
allowed_outbound_hosts = ["redis://*"]
key_value_stores = ["default"]

[component.eth-raw-transactions.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "eth_raw_transactions"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.eth-raw-transactions.variables]
redis_url = "{{ redis_url}}"
eth_api_url = "{{ eth_api_url }}"

[application.trigger.redis]
address = "{{ redis_url }}"

[[trigger.redis]]
channel = "eth_get_transactions"
component = "eth-get-transactions"

[component.eth-get-transactions]
source = "eth-get-transactions/target/wasm32-wasi/release/eth_get_transactions.wasm"
allowed_outbound_hosts = ["https://*", "redis://*"]

[component.eth-get-transactions.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "eth-get-transactions"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.eth-get-transactions.variables]
redis_url = "{{ redis_url}}"
eth_api_url = "{{ eth_api_url }}"
