# Generated by Django 4.2.7 on 2025-08-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credential_id", models.TextField(db_index=True, unique=True)),
                ("public_key", models.TextField()),
                ("name", models.CharField(blank=True, max_length=255)),
                ("aaguid", models.CharField(blank=True, max_length=36)),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                ("backup_eligible", models.BooleanField(default=False)),
                ("backup_state", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkey_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "passkey_devices",
                "ordering": ["-last_used_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="passkey_dev_user_id_b48be7_idx",
                    ),
                    models.Index(
                        fields=["credential_id"], name="passkey_dev_credent_d2503a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PasskeyChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "challenge",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("register", "Registration"),
                            ("authenticate", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "passkey_challenges",
                "indexes": [
                    models.Index(
                        fields=["challenge"], name="passkey_cha_challen_80e08f_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="passkey_cha_expires_29d42f_idx"
                    ),
                ],
            },
        ),
    ]
