# Generated by Django 4.2.7 on 2025-10-21 12:45

import inspect

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def _check_constraint_kwargs(condition):
    params = inspect.signature(models.CheckConstraint).parameters
    if "condition" in params:
        return {"condition": condition}
    return {"check": condition}


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("blockchain", "0006_remove_token_token_blockch_5f1d4f_idx_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_logins", models.IntegerField(default=0)),
                ("failed_logins", models.IntegerField(default=0)),
                ("unique_ips", models.JSONField(default=list)),
                ("typical_hours", models.JSONField(default=dict)),
                ("typical_days", models.JSONField(default=dict)),
                ("typical_locations", models.JSONField(default=list)),
                ("new_location_alerts", models.IntegerField(default=0)),
                ("permissions_used", models.JSONField(default=dict)),
                ("elevated_actions", models.IntegerField(default=0)),
                ("anomaly_score", models.IntegerField(default=0)),
                ("last_anomaly", models.DateTimeField(blank=True, null=True)),
                ("anomaly_reasons", models.JSONField(default=list)),
                ("analysis_start", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "access_patterns",
                "ordering": ["-anomaly_score", "-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="AlertChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_version",
                    models.IntegerField(
                        blank=True, help_text="NULL for creation", null=True
                    ),
                ),
                ("to_version", models.IntegerField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("template_instantiated", "Template Instantiated"),
                            ("params_updated", "Parameters Updated"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(help_text="List of field names that changed"),
                ),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField()),
                ("change_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Alert Change Log",
                "verbose_name_plural": "Alert Change Logs",
                "db_table": "alert_change_logs",
            },
        ),
        migrations.CreateModel(
            name="AlertExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_version",
                    models.IntegerField(help_text="Version of alert at execution time"),
                ),
                (
                    "trigger_mode",
                    models.CharField(
                        choices=[("event", "Event"), ("schedule", "Schedule")],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1, help_text="Retry attempt number (1, 2, 3...)"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, help_text="Maximum retry attempts"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "frozen_spec",
                    models.JSONField(help_text="Alert spec frozen at execution time"),
                ),
                (
                    "execution_context",
                    models.JSONField(
                        blank=True,
                        help_text="Event data, block number, timestamp, etc.",
                        null=True,
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        blank=True, help_text="NATS execution ID", max_length=255
                    ),
                ),
                (
                    "result",
                    models.BooleanField(
                        blank=True,
                        help_text="Alert condition result (True/False)",
                        null=True,
                    ),
                ),
                (
                    "result_value",
                    models.CharField(
                        blank=True,
                        help_text="Actual value that triggered alert",
                        max_length=255,
                    ),
                ),
                (
                    "result_metadata",
                    models.JSONField(
                        blank=True, help_text="Additional result context", null=True
                    ),
                ),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("rows_processed", models.IntegerField(blank=True, null=True)),
                (
                    "data_sources_used",
                    models.JSONField(
                        default=list, help_text="Data sources accessed during execution"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True, help_text="When job should execute", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Execution",
                "verbose_name_plural": "Alert Executions",
                "db_table": "alert_executions",
            },
        ),
        migrations.CreateModel(
            name="AlertGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("defi", "DeFi"),
                            ("whale", "Whale Movement"),
                            ("governance", "Governance"),
                            ("nft", "NFT"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "default_notification_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Default notification channels: ['email', 'webhook', 'sms']",
                    ),
                ),
                (
                    "default_cooldown_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Default cooldown period in minutes between notifications",
                    ),
                ),
                (
                    "aggregate_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to aggregate multiple alerts in a single notification",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this group can be cloned by others",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this group is visible to all users",
                    ),
                ),
                (
                    "subscription_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of active subscriptions to this group",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Group",
                "verbose_name_plural": "Alert Groups",
                "db_table": "alert_groups",
            },
        ),
        migrations.CreateModel(
            name="AlertGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within the group"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this alert is active in this group",
                    ),
                ),
                (
                    "settings_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override notification settings for this alert within this group",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Group Membership",
                "verbose_name_plural": "Alert Group Memberships",
                "db_table": "alert_group_memberships",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertGroupSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wallet_key",
                    models.CharField(
                        blank=True,
                        help_text="Format: CHAIN:subnet:address (for individual wallet subscriptions)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "settings_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override settings for all alerts in this group for these wallets",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Group Subscription",
                "verbose_name_plural": "Alert Group Subscriptions",
                "db_table": "alert_group_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="AlertInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "nl_description",
                    models.TextField(help_text="Original user prompt or description"),
                ),
                (
                    "template_params",
                    models.JSONField(
                        blank=True,
                        help_text="Parameters used for template instantiation: {'threshold': 1000, 'wallet': '0x123...'}",
                        null=True,
                    ),
                ),
                (
                    "_standalone_spec",
                    models.JSONField(
                        blank=True,
                        help_text="Complete alert specification for standalone alerts",
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_EVENT", "Account Event"),
                            ("ASSET_EVENT", "Asset Event"),
                            ("CONTRACT_INTERACTION", "Contract Interaction"),
                            ("PROTOCOL_EVENT", "Protocol Event"),
                            ("ANOMALY_EVENT", "Anomaly Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_event",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_CREATED", "Account Created"),
                            ("NATIVE_SEND", "Native Send"),
                            ("NATIVE_RECEIVE", "Native Receive"),
                            ("TOKEN_ALLOWANCE_CHANGED", "Token Allowance Changed"),
                            ("BALANCE_THRESHOLD", "Balance Threshold"),
                            ("GAS_USAGE_SPIKE", "Gas Usage Spike"),
                            ("TOKEN_MINT", "Token Mint"),
                            ("TOKEN_BURN", "Token Burn"),
                            ("TOKEN_TRANSFER", "Token Transfer"),
                            ("TOKEN_METADATA_UPDATE", "Token Metadata Update"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("BORROW", "Borrow"),
                            ("REPAY", "Repay"),
                            ("LIQUIDATION", "Liquidation"),
                            ("SWAP", "Swap"),
                            ("ADD_LIQUIDITY", "Add Liquidity"),
                            ("REMOVE_LIQUIDITY", "Remove Liquidity"),
                            ("BLOCK_PRODUCED", "Block Produced"),
                            ("CHAIN_REORG", "Chain Reorg"),
                            ("VALIDATOR_SLASHED", "Validator Slashed"),
                            ("LARGE_TRANSFER_OUTLIER", "Large Transfer Outlier"),
                            (
                                "PRIVILEGED_FUNCTION_CALLED",
                                "Privileged Function Called",
                            ),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_event_confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="Confidence score for sub-event classification",
                    ),
                ),
                (
                    "sub_event_proposed",
                    models.CharField(
                        blank=True,
                        help_text="Proposed sub-event if confidence < 0.8",
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain address of author",
                        max_length=42,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Instance",
                "verbose_name_plural": "Alert Instances",
                "db_table": "alert_instances",
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_EVENT", "Account Event"),
                            ("ASSET_EVENT", "Asset Event"),
                            ("CONTRACT_INTERACTION", "Contract Interaction"),
                            ("PROTOCOL_EVENT", "Protocol Event"),
                            ("ANOMALY_EVENT", "Anomaly Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sub_event",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_CREATED", "Account Created"),
                            ("NATIVE_SEND", "Native Send"),
                            ("NATIVE_RECEIVE", "Native Receive"),
                            ("TOKEN_ALLOWANCE_CHANGED", "Token Allowance Changed"),
                            ("BALANCE_THRESHOLD", "Balance Threshold"),
                            ("GAS_USAGE_SPIKE", "Gas Usage Spike"),
                            ("TOKEN_MINT", "Token Mint"),
                            ("TOKEN_BURN", "Token Burn"),
                            ("TOKEN_TRANSFER", "Token Transfer"),
                            ("TOKEN_METADATA_UPDATE", "Token Metadata Update"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAW", "Withdraw"),
                            ("BORROW", "Borrow"),
                            ("REPAY", "Repay"),
                            ("LIQUIDATION", "Liquidation"),
                            ("SWAP", "Swap"),
                            ("ADD_LIQUIDITY", "Add Liquidity"),
                            ("REMOVE_LIQUIDITY", "Remove Liquidity"),
                            ("BLOCK_PRODUCED", "Block Produced"),
                            ("CHAIN_REORG", "Chain Reorg"),
                            ("VALIDATOR_SLASHED", "Validator Slashed"),
                            ("LARGE_TRANSFER_OUTLIER", "Large Transfer Outlier"),
                            (
                                "PRIVILEGED_FUNCTION_CALLED",
                                "Privileged Function Called",
                            ),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nl_template",
                    models.TextField(
                        help_text="Natural language template with {{placeholders}}"
                    ),
                ),
                (
                    "spec_blueprint",
                    models.JSONField(
                        help_text="Alert specification template with {{placeholders}}"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        help_text="Array of variable descriptors: [{'name': 'threshold', 'type': 'number'}]"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all users"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Verified by admin"),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Template",
                "verbose_name_plural": "Alert Templates",
                "db_table": "alert_templates",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("LOGIN_FAILED", "Failed Login Attempt"),
                            ("CREATE", "Create Record"),
                            ("READ", "View Record"),
                            ("UPDATE", "Update Record"),
                            ("DELETE", "Delete Record"),
                            ("BULK_UPDATE", "Bulk Update"),
                            ("BULK_DELETE", "Bulk Delete"),
                            ("PERMISSION_GRANT", "Grant Permission"),
                            ("PERMISSION_REVOKE", "Revoke Permission"),
                            ("ROLE_CHANGE", "Role Change"),
                            ("CONFIG_CHANGE", "Configuration Change"),
                            ("SETTING_UPDATE", "Setting Update"),
                            ("DATA_EXPORT", "Data Export"),
                            ("REPORT_GENERATE", "Report Generation"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("MFA_ENABLE", "MFA Enabled"),
                            ("MFA_DISABLE", "MFA Disabled"),
                            ("API_KEY_CREATE", "API Key Created"),
                            ("API_KEY_REVOKE", "API Key Revoked"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("object_repr", models.CharField(max_length=500)),
                ("changes", models.JSONField(default=dict)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("UNAUTHORIZED", "Unauthorized"),
                            ("ERROR", "Error"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("risk_score", models.IntegerField(default=0)),
                ("requires_review", models.BooleanField(default=False)),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("checksum", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockchainNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("chain_name", models.CharField(max_length=100)),
                ("network", models.CharField(db_index=True, max_length=50)),
                ("subnet", models.CharField(default="mainnet", max_length=50)),
                (
                    "vm_type",
                    models.CharField(
                        choices=[
                            ("EVM", "Ethereum Virtual Machine"),
                            ("UTXO", "Unspent Transaction Output"),
                            ("SVM", "Solana Virtual Machine"),
                            ("COSMOS", "Cosmos SDK"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rpc_url", models.URLField(max_length=500)),
                ("ws_url", models.CharField(blank=True, max_length=500)),
                ("enabled", models.BooleanField(db_index=True, default=False)),
                ("is_primary", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=1)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "success_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blockchain_nodes",
                "ordering": ["network", "priority"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(max_length=100, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("GDPR", "GDPR Compliance"),
                            ("SOC2", "SOC 2 Audit"),
                            ("HIPAA", "HIPAA Compliance"),
                            ("PCI_DSS", "PCI-DSS Compliance"),
                            ("ACCESS_REVIEW", "Access Review"),
                            ("DATA_RETENTION", "Data Retention"),
                            ("SECURITY_AUDIT", "Security Audit"),
                            ("CHANGE_MANAGEMENT", "Change Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("executive_summary", models.TextField()),
                ("detailed_findings", models.JSONField(default=dict)),
                ("recommendations", models.JSONField(default=list)),
                ("evidence_audit_ids", models.JSONField(default=list)),
                ("compliance_score", models.IntegerField(default=0)),
                ("non_compliant_items", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_reports/"
                    ),
                ),
            ],
            options={
                "db_table": "compliance_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("widget_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("line_chart", "Line Chart"),
                            ("bar_chart", "Bar Chart"),
                            ("gauge", "Gauge"),
                            ("number", "Number Display"),
                            ("table", "Data Table"),
                            ("heatmap", "Heat Map"),
                            ("status_grid", "Status Grid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_types", models.JSONField(default=list)),
                ("components", models.JSONField(default=list)),
                ("position", models.JSONField(default=dict)),
                ("refresh_interval", models.IntegerField(default=5)),
                ("display_options", models.JSONField(default=dict)),
                (
                    "warning_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("required_permission", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_widgets",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=100, unique=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("AUDIT_LOG", "Audit Logs"),
                            ("SECURITY_EVENT", "Security Events"),
                            ("ACCESS_LOG", "Access Logs"),
                            ("CHANGE_LOG", "Change Logs"),
                            ("PERFORMANCE_LOG", "Performance Logs"),
                            ("DEBUG_LOG", "Debug Logs"),
                            ("USER_ACTIVITY", "User Activity Logs"),
                            ("SYSTEM_LOG", "System Logs"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("retention_days", models.IntegerField()),
                ("archive_after_days", models.IntegerField(blank=True, null=True)),
                ("legal_hold", models.BooleanField(default=False)),
                ("legal_hold_reason", models.TextField(blank=True)),
                ("legal_hold_until", models.DateField(blank=True, null=True)),
                ("auto_purge", models.BooleanField(default=True)),
                ("last_purge", models.DateTimeField(blank=True, null=True)),
                ("next_purge", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_retention_policies",
                "ordering": ["log_type"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetterMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_subject", models.CharField(max_length=200)),
                ("message_id", models.CharField(max_length=100, unique=True)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(blank=True, null=True)),
                ("error_type", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
                ("failure_count", models.IntegerField(default=1)),
                ("original_timestamp", models.DateTimeField()),
                ("dlq_timestamp", models.DateTimeField(auto_now_add=True)),
                ("last_retry", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "nats_dead_letter_messages",
                "ordering": ["-dlq_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeltaLakeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=200)),
                ("database_name", models.CharField(max_length=100)),
                ("location", models.TextField()),
                ("size_bytes", models.BigIntegerField()),
                ("file_count", models.IntegerField()),
                ("partition_count", models.IntegerField()),
                ("row_count", models.BigIntegerField()),
                ("last_modified", models.DateTimeField()),
                (
                    "avg_query_time",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "daily_ingestion_gb",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_compaction", models.DateTimeField(blank=True, null=True)),
                ("last_vacuum", models.DateTimeField(blank=True, null=True)),
                ("needs_optimization", models.BooleanField(default=False)),
                ("properties", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "delta_lake_tables",
                "ordering": ["database_name", "table_name"],
            },
        ),
        migrations.CreateModel(
            name="GroupNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mandatory_channels",
                    models.JSONField(
                        default=list,
                        help_text="Channels that all group members must receive notifications on",
                    ),
                ),
                (
                    "escalation_rules",
                    models.JSONField(
                        default=dict,
                        help_text="Escalation paths and timing for different priority levels",
                    ),
                ),
                (
                    "shared_channels",
                    models.JSONField(
                        default=dict,
                        help_text="Shared notification channels for the entire group",
                    ),
                ),
                (
                    "member_overrides_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Allow group members to override certain settings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Group Notification Settings",
                "verbose_name_plural": "Group Notification Settings",
                "db_table": "group_notification_settings",
            },
        ),
        migrations.CreateModel(
            name="InfrastructureAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=100, unique=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alert_type", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("resolved", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "infrastructure_alerts",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_id", models.CharField(max_length=100, unique=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("REDIS", "Redis Cache"),
                            ("NATS", "NATS Messaging"),
                            ("DELTA_LAKE", "Delta Lake Storage"),
                            ("WASMCLOUD", "wasmCloud Runtime"),
                            ("POSTGRESQL", "PostgreSQL Database"),
                            ("MONITORING", "Monitoring Stack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("config", models.JSONField(default=dict)),
                ("connection_string", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_healthy", models.BooleanField(default=True)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "infrastructure_components",
                "ordering": ["component_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="NATSStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_name", models.CharField(max_length=100, unique=True)),
                ("subjects", models.JSONField(default=list)),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("limits", "Limits"),
                            ("interest", "Interest"),
                            ("work_queue", "Work Queue"),
                        ],
                        default="limits",
                        max_length=20,
                    ),
                ),
                ("retention_days", models.IntegerField(default=7)),
                ("max_messages", models.BigIntegerField(blank=True, null=True)),
                ("max_bytes", models.BigIntegerField(blank=True, null=True)),
                ("message_count", models.BigIntegerField(default=0)),
                ("bytes_used", models.BigIntegerField(default=0)),
                ("consumer_count", models.IntegerField(default=0)),
                ("first_sequence", models.BigIntegerField(blank=True, null=True)),
                ("last_sequence", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nats_streams",
                "ordering": ["stream_name"],
            },
        ),
        migrations.CreateModel(
            name="WebSocketConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("connection_id", models.CharField(max_length=100, unique=True)),
                ("channel_name", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("subscribed_metrics", models.JSONField(default=list)),
                ("subscribed_components", models.JSONField(default=list)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_ping", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websocket_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "websocket_connections",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="WasmCloudProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(max_length=100, unique=True)),
                ("provider_name", models.CharField(max_length=200)),
                ("provider_type", models.CharField(max_length=100)),
                ("active_connections", models.IntegerField()),
                ("total_connections", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("DEGRADED", "Degraded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("errors_per_min", models.IntegerField(default=0)),
                ("version", models.CharField(max_length=50)),
                ("capabilities", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wasmcloud_providers",
                        to="app.infrastructurecomponent",
                    ),
                ),
            ],
            options={
                "db_table": "wasmcloud_providers",
                "ordering": ["provider_type", "provider_name"],
            },
        ),
        migrations.CreateModel(
            name="WasmCloudActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.CharField(max_length=100, unique=True)),
                ("actor_name", models.CharField(max_length=200)),
                ("actor_type", models.CharField(max_length=100)),
                ("cpu_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("memory_mb", models.IntegerField()),
                ("messages_per_sec", models.IntegerField()),
                (
                    "average_latency_ms",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("error_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("instance_count", models.IntegerField(default=1)),
                ("desired_count", models.IntegerField(default=1)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DEGRADED", "Degraded"),
                            ("UNHEALTHY", "Unhealthy"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("capabilities", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wasmcloud_actors",
                        to="app.infrastructurecomponent",
                    ),
                ),
            ],
            options={
                "db_table": "wasmcloud_actors",
                "ordering": ["actor_type", "actor_name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "websocket_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable WebSocket real-time notifications (default enabled per PRD)",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Master toggle for all notifications"
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=dict,
                        help_text="Channel-specific settings (email, slack, sms, etc.)",
                    ),
                ),
                (
                    "priority_routing",
                    models.JSONField(
                        default=dict,
                        help_text="Mapping of priority levels to preferred notification channels",
                    ),
                ),
                (
                    "quiet_hours",
                    models.JSONField(
                        blank=True,
                        help_text="Quiet hours configuration with timezone and priority overrides",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Settings",
                "verbose_name_plural": "User Notification Settings",
                "db_table": "user_notification_settings",
            },
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("BLOCKCHAIN", "Blockchain"),
                            ("ALERT", "Alert System"),
                            ("USER", "User Activity"),
                            ("SECURITY", "Security"),
                            ("PERFORMANCE", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("component", models.CharField(max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RedisMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memory_used", models.BigIntegerField()),
                ("memory_max", models.BigIntegerField()),
                ("memory_rss", models.BigIntegerField()),
                ("hit_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("miss_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("eviction_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("connected_clients", models.IntegerField()),
                ("blocked_clients", models.IntegerField()),
                ("ops_per_sec", models.IntegerField()),
                ("instantaneous_ops", models.IntegerField()),
                ("latency_avg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latency_p99", models.DecimalField(decimal_places=2, max_digits=10)),
                ("key_patterns", models.JSONField(default=dict)),
                ("total_keys", models.BigIntegerField()),
                ("expired_keys", models.BigIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redis_metrics",
                        to="app.infrastructurecomponent",
                    ),
                ),
            ],
            options={
                "db_table": "redis_metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("CPU_USAGE", "CPU Usage %"),
                            ("MEMORY_USAGE", "Memory Usage %"),
                            ("DISK_USAGE", "Disk Usage %"),
                            ("NETWORK_IO", "Network I/O"),
                            ("ACTIVE_USERS", "Active Users"),
                            ("REQUESTS_PER_SEC", "Requests/sec"),
                            ("RESPONSE_TIME", "Response Time (ms)"),
                            ("ERROR_RATE", "Error Rate %"),
                            ("BLOCKS_PROCESSED", "Blocks Processed/min"),
                            ("TRANSACTIONS_PROCESSED", "Transactions/sec"),
                            ("CHAIN_HEIGHT", "Chain Height"),
                            ("NODE_SYNC_STATUS", "Node Sync %"),
                            ("ALERTS_EVALUATED", "Alerts Evaluated/min"),
                            ("ALERTS_TRIGGERED", "Alerts Triggered/min"),
                            ("ALERT_QUEUE_DEPTH", "Alert Queue Depth"),
                            ("ALERT_PROCESSING_TIME", "Alert Processing Time (ms)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("component", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_anomaly", models.BooleanField(default=False)),
                ("threshold_exceeded", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "realtime_metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "timestamp"],
                        name="realtime_me_metric__5c5a53_idx",
                    ),
                    models.Index(
                        fields=["component", "timestamp"],
                        name="realtime_me_compone_d3f590_idx",
                    ),
                    models.Index(
                        fields=["is_anomaly", "timestamp"],
                        name="realtime_me_is_anom_dbeedb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("balance_alert", "Balance Alert"),
                            ("transaction_alert", "Transaction Alert"),
                            ("price_alert", "Price Alert"),
                            ("security_alert", "Security Alert"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("sms", "SMS"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("webhook", "Webhook"),
                            ("websocket", "WebSocket"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="Subject line template (email/notifications)",
                        max_length=200,
                    ),
                ),
                ("text_template", models.TextField(help_text="Plain text template")),
                (
                    "html_template",
                    models.TextField(
                        blank=True,
                        help_text="HTML template for rich content channels",
                        null=True,
                    ),
                ),
                (
                    "structured_template",
                    models.JSONField(
                        blank=True,
                        help_text="Structured template for channels like Slack blocks",
                        null=True,
                    ),
                ),
                (
                    "required_variables",
                    models.JSONField(
                        default=list, help_text="List of required template variables"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "unique_together": {("template_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.UUIDField(
                        help_text="Unique identifier for the notification request"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Notification channel (email, slack, sms, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("channel_disabled", "Channel Disabled"),
                            ("quiet_hours", "Quiet Hours"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from external provider (SendGrid, Twilio, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True,
                        help_text="Full response from external provider",
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to="app.alertinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "db_table": "notification_deliveries",
            },
        ),
        migrations.CreateModel(
            name="NATSControlCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("START_ACTOR", "Start wasmCloud Actor"),
                            ("STOP_ACTOR", "Stop wasmCloud Actor"),
                            ("SCALE_ACTOR", "Scale wasmCloud Actor"),
                            ("UPDATE_CONFIG", "Update Configuration"),
                            ("HEALTH_CHECK", "Health Check"),
                            ("RELOAD_PROVIDER", "Reload Provider"),
                            ("PAUSE_PROCESSING", "Pause Processing"),
                            ("RESUME_PROCESSING", "Resume Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_actor", models.CharField(max_length=100)),
                ("target_provider", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nats_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nats_control_commands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NATSConsumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_name", models.CharField(max_length=100)),
                ("durable_name", models.CharField(blank=True, max_length=100)),
                ("filter_subject", models.CharField(blank=True, max_length=200)),
                (
                    "ack_policy",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit"),
                            ("none", "None"),
                            ("all", "All"),
                        ],
                        default="explicit",
                        max_length=20,
                    ),
                ),
                ("max_deliver", models.IntegerField(default=5)),
                ("pending_messages", models.IntegerField(default=0)),
                ("delivered_messages", models.BigIntegerField(default=0)),
                ("ack_floor", models.BigIntegerField(default=0)),
                ("num_redelivered", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_paused", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumers",
                        to="app.natsstream",
                    ),
                ),
            ],
            options={
                "db_table": "nats_consumers",
                "ordering": ["stream", "consumer_name"],
            },
        ),
        migrations.AddIndex(
            model_name="infrastructurecomponent",
            index=models.Index(
                fields=["component_type", "is_active"],
                name="infrastruct_compone_411c0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructurecomponent",
            index=models.Index(
                fields=["is_healthy", "last_health_check"],
                name="infrastruct_is_heal_f7fbef_idx",
            ),
        ),
        migrations.AddField(
            model_name="infrastructurealert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_infra_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="infrastructurealert",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infra_alerts",
                to="app.infrastructurecomponent",
            ),
        ),
        migrations.AddField(
            model_name="groupnotificationsettings",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to="organizations.team",
            ),
        ),
        migrations.AddField(
            model_name="deltalaketable",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delta_tables",
                to="app.infrastructurecomponent",
            ),
        ),
        migrations.AddField(
            model_name="deadlettermessage",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_dlq_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deadlettermessage",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dead_letters",
                to="app.natsstream",
            ),
        ),
        migrations.AddField(
            model_name="dataretentionpolicy",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retention_policy_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancereport",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainnode",
            index=models.Index(
                fields=["network", "enabled"], name="blockchain__network_fb4766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockchainnode",
            index=models.Index(
                fields=["vm_type", "enabled"], name="blockchain__vm_type_c025ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockchainnode",
            unique_together={("network", "subnet", "is_primary")},
        ),
        migrations.AddField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alerttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="app.alerttemplate",
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertgroupsubscription",
            name="alert_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="app.alertgroup",
            ),
        ),
        migrations.AddField(
            model_name="alertgroupsubscription",
            name="subscribed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_group_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertgroupsubscription",
            name="wallet_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_group_subscriptions",
                to="blockchain.walletgroup",
            ),
        ),
        migrations.AddField(
            model_name="alertgroupmembership",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_group_additions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertgroupmembership",
            name="alert_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="app.alertgroup",
            ),
        ),
        migrations.AddField(
            model_name="alertgroupmembership",
            name="alert_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="app.alertinstance",
            ),
        ),
        migrations.AddField(
            model_name="alertgroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_alert_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alertexecution",
            name="alert_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="app.alertinstance",
            ),
        ),
        migrations.AddField(
            model_name="alertchangelog",
            name="alert_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_logs",
                to="app.alertinstance",
            ),
        ),
        migrations.AddField(
            model_name="alertchangelog",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="accesspattern",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_patterns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="websocketconnection",
            index=models.Index(
                fields=["user", "is_active"], name="websocket_c_user_id_0bac24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="websocketconnection",
            index=models.Index(
                fields=["is_active", "last_ping"], name="websocket_c_is_acti_31ea37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wasmcloudactor",
            index=models.Index(
                fields=["component", "health_status"],
                name="wasmcloud_a_compone_c9ddc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["level", "timestamp"], name="system_even_level_692ee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["category", "timestamp"], name="system_even_categor_4a41a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["is_acknowledged", "timestamp"],
                name="system_even_is_ackn_7009bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="redismetrics",
            index=models.Index(
                fields=["component", "timestamp"], name="redis_metri_compone_5277b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification_id"], name="notificatio_notific_9901ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_ed32fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["alert", "status"], name="notificatio_alert_i_a37c9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel", "status"], name="notificatio_channel_169003_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="natscontrolcommand",
            index=models.Index(
                fields=["status", "created_at"], name="nats_contro_status_c25647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="natscontrolcommand",
            index=models.Index(
                fields=["command_type", "status"], name="nats_contro_command_14ebd1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="natsconsumer",
            unique_together={("stream", "consumer_name")},
        ),
        migrations.AddIndex(
            model_name="infrastructurealert",
            index=models.Index(
                fields=["component", "is_active"], name="infrastruct_compone_5f14fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="infrastructurealert",
            index=models.Index(
                fields=["severity", "is_active"], name="infrastruct_severit_ece900_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deltalaketable",
            unique_together={("component", "database_name", "table_name")},
        ),
        migrations.AddIndex(
            model_name="deadlettermessage",
            index=models.Index(
                fields=["is_resolved", "dlq_timestamp"],
                name="nats_dead_l_is_reso_e53943_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deadlettermessage",
            index=models.Index(
                fields=["stream", "original_subject"],
                name="nats_dead_l_stream__0d366b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(
                fields=["report_type", "generated_at"],
                name="compliance__report__9c531e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancereport",
            index=models.Index(
                fields=["start_date", "end_date"], name="compliance__start_d_f25f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="audit_logs_action__11f9f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_logs_content_b0ef47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["risk_score", "timestamp"], name="audit_logs_risk_sc_1f05bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["requires_review", "timestamp"],
                name="audit_logs_require_ed9203_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["event_type", "sub_event"],
                name="alert_templ_event_t_83802d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["is_public", "is_verified"],
                name="alert_templ_is_publ_ab2fec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["usage_count"], name="alert_templ_usage_c_2f2686_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["created_by"], name="alert_templ_created_54f76a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["user", "enabled"], name="alert_insta_user_id_75765d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["event_type", "sub_event"],
                name="alert_insta_event_t_f7218e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["template"], name="alert_insta_templat_c3c906_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["created_at"], name="alert_insta_created_84e6cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["version"], name="alert_insta_version_aac3d2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertinstance",
            unique_together={("id", "version")},
        ),
        migrations.AddIndex(
            model_name="alertgroupsubscription",
            index=models.Index(
                fields=["alert_group", "is_active"],
                name="alert_group_alert_g_e83f6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupsubscription",
            index=models.Index(
                fields=["wallet_group", "is_active"],
                name="alert_group_wallet__ba7246_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupsubscription",
            index=models.Index(
                fields=["wallet_key", "is_active"],
                name="alert_group_wallet__afc298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupsubscription",
            index=models.Index(
                fields=["subscribed_by"], name="alert_group_subscri_db8a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupsubscription",
            index=models.Index(
                fields=["created_at"], name="alert_group_created_1d20d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alertgroupsubscription",
            constraint=models.CheckConstraint(
                **_check_constraint_kwargs(
                    models.Q(
                        models.Q(
                            ("wallet_group__isnull", False),
                            ("wallet_key__isnull", True),
                        ),
                        models.Q(
                            ("wallet_group__isnull", True),
                            ("wallet_key__isnull", False),
                        ),
                        _connector="OR",
                    ),
                ),
                name="subscription_to_either_group_or_wallet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertgroupsubscription",
            unique_together={
                ("alert_group", "wallet_key"),
                ("alert_group", "wallet_group"),
            },
        ),
        migrations.AddIndex(
            model_name="alertgroupmembership",
            index=models.Index(
                fields=["alert_group", "is_active"],
                name="alert_group_alert_g_e64d0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupmembership",
            index=models.Index(
                fields=["alert_instance", "is_active"],
                name="alert_group_alert_i_3cb1fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupmembership",
            index=models.Index(
                fields=["alert_group", "order"], name="alert_group_alert_g_d122af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroupmembership",
            index=models.Index(
                fields=["created_at"], name="alert_group_created_169e71_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertgroupmembership",
            unique_together={("alert_group", "alert_instance")},
        ),
        migrations.AddIndex(
            model_name="alertgroup",
            index=models.Index(
                fields=["created_by"], name="alert_group_created_d788ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroup",
            index=models.Index(
                fields=["category"], name="alert_group_categor_60ac5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroup",
            index=models.Index(
                fields=["is_template"], name="alert_group_is_temp_84a1be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroup",
            index=models.Index(
                fields=["is_public"], name="alert_group_is_publ_ee6e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertgroup",
            index=models.Index(
                fields=["created_at"], name="alert_group_created_783b86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(
                fields=["alert_instance", "alert_version"],
                name="alert_execu_alert_i_6f5d8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(
                fields=["status", "priority"], name="alert_execu_status_fecc45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(
                fields=["trigger_mode"], name="alert_execu_trigger_b7b746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(
                fields=["queued_at"], name="alert_execu_queued__c4c092_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(
                fields=["started_at"], name="alert_execu_started_2a9914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(fields=["due_at"], name="alert_execu_due_at_8b151c_idx"),
        ),
        migrations.AddIndex(
            model_name="alertexecution",
            index=models.Index(fields=["result"], name="alert_execu_result_b9435f_idx"),
        ),
        migrations.AddIndex(
            model_name="alertchangelog",
            index=models.Index(
                fields=["alert_instance", "to_version"],
                name="alert_chang_alert_i_9d63c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertchangelog",
            index=models.Index(
                fields=["created_at"], name="alert_chang_created_8cb331_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertchangelog",
            index=models.Index(
                fields=["change_type"], name="alert_chang_change__9e40f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesspattern",
            index=models.Index(
                fields=["user", "anomaly_score"], name="access_patt_user_id_869feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesspattern",
            index=models.Index(
                fields=["anomaly_score", "last_updated"],
                name="access_patt_anomaly_849a25_idx",
            ),
        ),
    ]
