# Generated by Django 4.2.7 on 2025-10-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertgroup",
            name="parent_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parent alert groups from which this group inherits alerts and subscribers",
                related_name="child_groups",
                to="app.alertgroup",
            ),
        ),
        migrations.AddField(
            model_name="alertgroup",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who subscribe to this alert group directly",
                related_name="direct_alert_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_user_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Group",
                "verbose_name_plural": "User Groups",
                "db_table": "user_groups",
            },
        ),
        migrations.AddField(
            model_name="alertgroup",
            name="user_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="User groups that subscribe to this alert group",
                related_name="alert_groups",
                to="app.usergroup",
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["created_by"], name="user_groups_created_9dac3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(fields=["name"], name="user_groups_name_4587ce_idx"),
        ),
        migrations.AddIndex(
            model_name="usergroup",
            index=models.Index(
                fields=["created_at"], name="user_groups_created_181e3d_idx"
            ),
        ),
    ]
