# Generated by Django 4.2.7 on 2025-10-24 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("app", "0002_add_user_groups_and_alert_nesting"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannelEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("user", "User"), ("team", "Team")],
                        db_index=True,
                        help_text="Owner type: 'user' or 'team'",
                        max_length=10,
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the owning user or team"
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("slack", "Slack"),
                            ("webhook", "Webhook"),
                            ("sms", "SMS"),
                        ],
                        db_index=True,
                        help_text="Notification channel type",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-friendly label (e.g., 'Work Email', 'Trading Telegram')",
                        max_length=100,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="Channel-specific configuration (address, webhook_url, chat_id, etc.)"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this endpoint is currently enabled",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this endpoint has been verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last verification",
                        null=True,
                    ),
                ),
                (
                    "routing_mode",
                    models.CharField(
                        choices=[
                            ("all_enabled", "All Enabled"),
                            ("priority_based", "Priority Based"),
                        ],
                        default="all_enabled",
                        help_text="Routing mode: 'all_enabled' or 'priority_based'",
                        max_length=20,
                    ),
                ),
                (
                    "priority_filters",
                    models.JSONField(
                        default=list,
                        help_text="Priority levels to receive in priority_based mode (e.g., ['critical', 'high'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this endpoint",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notification_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel Endpoint",
                "verbose_name_plural": "Notification Channel Endpoints",
                "db_table": "notification_channel_endpoints",
            },
        ),
        migrations.CreateModel(
            name="TeamMemberNotificationOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "team_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch - disables ALL team notifications if False",
                    ),
                ),
                (
                    "disabled_endpoints",
                    models.JSONField(
                        default=list,
                        help_text="List of NotificationChannelEndpoint UUIDs disabled for this member",
                    ),
                ),
                (
                    "disabled_priorities",
                    models.JSONField(
                        default=list,
                        help_text="Priority levels disabled across ALL team endpoints (e.g., ['low', 'normal'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Team member who created this override",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_notification_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team for which this override applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_notification_overrides",
                        to="organizations.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member Notification Override",
                "verbose_name_plural": "Team Member Notification Overrides",
                "db_table": "team_member_notification_overrides",
                "indexes": [
                    models.Index(
                        fields=["team", "member", "team_notifications_enabled"],
                        name="team_member_team_id_caca09_idx",
                    )
                ],
                "unique_together": {("team", "member")},
            },
        ),
        migrations.CreateModel(
            name="NotificationChannelVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        help_text="6-digit verification code", max_length=6
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Verification"),
                            ("re_enable", "Re-Enable Verification"),
                        ],
                        help_text="Type of verification: initial or re-enable",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Expiration timestamp for verification code"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when verification was completed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts"
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        help_text="Endpoint being verified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="app.notificationchannelendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel Verification",
                "verbose_name_plural": "Notification Channel Verifications",
                "db_table": "notification_channel_verifications",
                "indexes": [
                    models.Index(
                        fields=["endpoint", "expires_at"],
                        name="notificatio_endpoin_645563_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notificationchannelendpoint",
            index=models.Index(
                fields=["owner_type", "owner_id", "enabled"],
                name="notificatio_owner_t_3091e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannelendpoint",
            index=models.Index(
                fields=["channel_type", "enabled", "verified"],
                name="notificatio_channel_f817fe_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationchannelendpoint",
            constraint=models.UniqueConstraint(
                fields=("owner_type", "owner_id", "channel_type", "label"),
                name="unique_endpoint_label_per_owner_channel",
            ),
        ),
    ]
