# Generated by Django 4.2.7 on 2025-10-24 06:39

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def migrate_user_notification_settings_to_endpoints(apps, schema_editor):
    """
    Migrate existing UserNotificationSettings channels to NotificationChannelEndpoint format.

    For each user with notification settings, create individual NotificationChannelEndpoint
    records for each enabled channel in their old settings.
    """
    UserNotificationSettings = apps.get_model('app', 'UserNotificationSettings')
    NotificationChannelEndpoint = apps.get_model('app', 'NotificationChannelEndpoint')

    migrated_count = 0
    skipped_count = 0

    for user_settings in UserNotificationSettings.objects.all():
        channels = user_settings.channels or {}

        for channel_type, channel_config in channels.items():
            # Only migrate enabled channels
            if not channel_config.get('enabled', False):
                skipped_count += 1
                continue

            # Skip websocket channel (handled separately)
            if channel_type == 'websocket':
                continue

            # Extract config
            config = channel_config.get('config', {})
            if not config:
                logger.warning(
                    f"Skipping {channel_type} for user {user_settings.user_id}: empty config"
                )
                skipped_count += 1
                continue

            # Create endpoint with auto-generated label
            try:
                NotificationChannelEndpoint.objects.create(
                    owner_type='user',
                    owner_id=user_settings.user_id,
                    channel_type=channel_type,
                    label=f"Default {channel_type.title()}",  # Auto-generated label
                    config=config,
                    enabled=channel_config.get('enabled', True),
                    verified=channel_config.get('verified', False),
                    routing_mode='all_enabled',  # Default to all_enabled
                    priority_filters=[],  # Empty priority filters for backward compatibility
                    created_by_id=user_settings.user_id,
                )
                migrated_count += 1
                logger.info(
                    f"Migrated {channel_type} endpoint for user {user_settings.user_id}"
                )
            except Exception as e:
                logger.error(
                    f"Failed to migrate {channel_type} for user {user_settings.user_id}: {e}"
                )
                skipped_count += 1

    logger.info(
        f"Migration complete: {migrated_count} endpoints created, {skipped_count} skipped"
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: delete all user-owned NotificationChannelEndpoints.

    WARNING: This will delete all endpoint data. Use with caution.
    """
    NotificationChannelEndpoint = apps.get_model('app', 'NotificationChannelEndpoint')

    deleted_count = NotificationChannelEndpoint.objects.filter(owner_type='user').delete()[0]
    logger.info(f"Reverse migration: deleted {deleted_count} user endpoints")


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_add_multi_address_notification_endpoints"),
    ]

    operations = [
        migrations.RunPython(
            migrate_user_notification_settings_to_endpoints,
            reverse_code=reverse_migration,
        ),
    ]
