# Generated by Django 4.2.7 on 2025-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_migrate_existing_notification_settings_to_endpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannelendpoint",
            name="priority_filters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Priority levels to receive in priority_based mode (e.g., ['critical', 'high'])",
            ),
        ),
    ]
