# Generated by Django 4.2.7 on 2025-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_fix_priority_filters_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertinstance",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("event_driven", "Event-Driven"),
                    ("one_time", "One-Time"),
                    ("periodic", "Periodic"),
                ],
                default="event_driven",
                help_text="Determines how AlertJobs are created for this alert",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="trigger_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="""Configuration for job creation based on trigger_type:
        event_driven: {"chains": ["ethereum"], "event_types": ["transfer"]} - created by blockchain actors
        one_time: {"reset_allowed": true} - created once by Alert Scheduler Provider
        periodic: {"interval_seconds": 300, "schedule": "*/5 * * * *"} - created on schedule by provider""",
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="last_job_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last AlertJob creation (used for periodic scheduling)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="job_creation_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of AlertJobs created for this alert (debugging/analytics)",
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["trigger_type", "enabled"], name="app_alertin_trigger_idx"
            ),
        ),
    ]
