# Generated by Django migration
# Phase 8: Alert Validation Strategy

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_trigger_config_to_alertinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='validation_schema',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="""JSON schema for frontend form generation and validation.
        {
            "alert_type": "wallet|network|token",
            "target_config": {
                "min_targets": 1,
                "max_targets": 100,
                "allow_groups": true,
                "allow_individual": true,
                "key_pattern": "^[A-Z]+:[a-z\\-]+:(0x[a-fA-F0-9]+|[a-zA-Z0-9]+)$",
                "supported_chains": ["ETH", "SOL", "BTC", "AVAX"]
            },
            "variables": [
                {
                    "name": "threshold",
                    "type": "number",
                    "required": true,
                    "label": "Threshold Value",
                    "description": "Alert triggers when value exceeds this",
                    "ui_component": "currency_input",
                    "validation": {"min": 0, "max": 1000000, "unit": "USD"},
                    "default": null
                }
            ]
        }"""
            ),
        ),
    ]
