# Generated by Django 4.2.7 on 2025-12-01 13:57

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0007_alerttemplate_validation_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet Group"),
                            ("alert", "Alert Group"),
                            ("user", "User Group"),
                            ("network", "Network Group"),
                            ("token", "Token Group"),
                            ("contract", "Contract Group"),
                            ("nft", "NFT Collection Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Group-specific settings: {'is_default': true, 'network_filter': 'mainnet'}",
                    ),
                ),
                (
                    "member_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Format: {"members": {"key1": {metadata}, "key2": {metadata}}}',
                    ),
                ),
                ("member_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Generic Group",
                "verbose_name_plural": "Generic Groups",
                "db_table": "generic_groups",
            },
        ),
        migrations.CreateModel(
            name="GroupSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Override settings for alerts in this subscription",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Group Subscription",
                "verbose_name_plural": "Group Subscriptions",
                "db_table": "group_subscriptions",
            },
        ),
        migrations.RenameIndex(
            model_name="alertinstance",
            new_name="alert_insta_trigger_e2d36e_idx",
            old_name="app_alertin_trigger_idx",
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Alert"),
                    ("network", "Network Alert"),
                    ("token", "Token Alert"),
                ],
                default="wallet",
                help_text="Type of alert: wallet, network, or token - determines valid target types",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="processing_error",
            field=models.TextField(
                blank=True, help_text="Error message if NLP processing failed"
            ),
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="skipped",
                help_text="NLP processing status for NL-to-spec conversion",
                max_length=20,
            ),
        ),
        # Add GenericGroup owner first (needed for ForeignKey references)
        migrations.AddField(
            model_name="genericgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add target_group field to AlertInstance BEFORE creating index on it
        migrations.AddField(
            model_name="alertinstance",
            name="target_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Target group (wallet/network/token group) for this alert",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_instances",
                to="app.genericgroup",
            ),
        ),
        # Now add AlertInstance indexes (after target_group field exists)
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["processing_status"], name="alert_insta_process_0901b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["alert_type", "enabled"], name="alert_insta_alert_t_8f8215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=models.Index(
                fields=["target_group", "enabled"],
                name="alert_insta_target__fbdf25_idx",
            ),
        ),
        # Add GroupSubscription foreign keys
        migrations.AddField(
            model_name="groupsubscription",
            name="alert_group",
            field=models.ForeignKey(
                limit_choices_to={"group_type": "alert"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_subscriptions",
                to="app.genericgroup",
            ),
        ),
        migrations.AddField(
            model_name="groupsubscription",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupsubscription",
            name="target_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_to_alerts",
                to="app.genericgroup",
            ),
        ),
        # GroupSubscription indexes
        migrations.AddIndex(
            model_name="groupsubscription",
            index=models.Index(
                fields=["alert_group", "is_active"],
                name="group_subsc_alert_g_973436_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubscription",
            index=models.Index(
                fields=["target_group", "is_active"],
                name="group_subsc_target__57e87a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubscription",
            index=models.Index(
                fields=["owner", "is_active"], name="group_subsc_owner_i_46d7ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsubscription",
            index=models.Index(
                fields=["created_at"], name="group_subsc_created_c7991c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupsubscription",
            unique_together={("alert_group", "target_group")},
        ),
        # GenericGroup indexes
        migrations.AddIndex(
            model_name="genericgroup",
            index=models.Index(
                fields=["group_type", "owner"], name="generic_gro_group_t_0b1c9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genericgroup",
            index=models.Index(
                fields=["owner", "created_at"], name="generic_gro_owner_i_ba3995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="genericgroup",
            index=models.Index(
                fields=["group_type", "created_at"],
                name="generic_gro_group_t_585a9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="genericgroup",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["member_data"], name="generic_group_member_gin"
            ),
        ),
    ]
