# Generated by Django 4.2.7 on 2025-12-01 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_genericgroup_groupsubscription_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardWidget",
        ),
        migrations.DeleteModel(
            name="RealTimeMetric",
        ),
        migrations.DeleteModel(
            name="AccessPattern",
        ),
        migrations.DeleteModel(
            name="AlertGroup",
        ),
        migrations.DeleteModel(
            name="AlertGroupMembership",
        ),
        migrations.DeleteModel(
            name="AlertGroupSubscription",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="ComplianceReport",
        ),
        migrations.DeleteModel(
            name="DataRetentionPolicy",
        ),
        migrations.DeleteModel(
            name="DeadLetterMessage",
        ),
        migrations.DeleteModel(
            name="DeltaLakeTable",
        ),
        migrations.DeleteModel(
            name="InfrastructureAlert",
        ),
        migrations.DeleteModel(
            name="InfrastructureComponent",
        ),
        migrations.DeleteModel(
            name="NATSConsumer",
        ),
        migrations.DeleteModel(
            name="NATSControlCommand",
        ),
        migrations.DeleteModel(
            name="NATSStream",
        ),
        migrations.DeleteModel(
            name="RedisMetrics",
        ),
        migrations.DeleteModel(
            name="SystemEvent",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
        migrations.DeleteModel(
            name="WasmCloudActor",
        ),
        migrations.DeleteModel(
            name="WasmCloudProvider",
        ),
        migrations.DeleteModel(
            name="WebSocketConnection",
        ),
    ]
