# Generated by Django 4.2.7 on 2025-12-04 16:40

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blockchain", "0007_alter_walletgroupmembership_unique_together_and_more"),
        ("app", "0009_remove_accesspattern_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultNetworkAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subnet",
                    models.CharField(
                        default="mainnet",
                        help_text="Network subnet (mainnet, testnet, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this default alert is active"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Default settings applied to alerts using this template:\n        {\n            "default_priority": "normal",\n            "cooldown_minutes": 5,\n            "max_notifications_per_hour": 100\n        }',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Default Network Alert",
                "verbose_name_plural": "Default Network Alerts",
                "db_table": "default_network_alerts",
            },
        ),
        migrations.CreateModel(
            name="UserWalletGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wallet_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='User\'s wallet keys managed by the provider.\n        Format: ["ETH:mainnet:0x123...", "SOL:mainnet:ABC..."]\n        IMPORTANT: Only the provider can modify this field.',
                    ),
                ),
                (
                    "auto_subscribe_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically subscribe user to alerts on this group",
                    ),
                ),
                (
                    "notification_routing",
                    models.CharField(
                        choices=[
                            ("callback_only", "Callback Only"),
                            ("user_channels", "User Channels"),
                            ("both", "Both"),
                        ],
                        default="callback_only",
                        help_text="How notifications are delivered: callback only, user channels, or both",
                        max_length=20,
                    ),
                ),
                (
                    "access_control",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Access control for who can edit this UserWalletGroup.\n        {\n            "editors": {\n                "users": ["user-uuid-1", "user-uuid-2"],\n                "api_keys": ["api-key-id-1"]\n            }\n        }',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Wallet Group",
                "verbose_name_plural": "User Wallet Groups",
                "db_table": "user_wallet_groups",
            },
        ),
        migrations.AddField(
            model_name="alertinstance",
            name="target_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Individual target keys for fine-grained targeting.\n        Format: ["ETH:mainnet:0x123...", "SOL:mainnet:ABC..."]\n\n        Targeting Resolution:\n        1. If target_keys is set → use individual keys (specific wallets)\n        2. Else if target_group is set → use all members in group\n        3. Else → alert applies globally (based on spec.scope)\n        ',
            ),
        ),
        migrations.AddIndex(
            model_name="alertinstance",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["target_keys"], name="alert_instance_target_keys_gin"
            ),
        ),
        migrations.AddField(
            model_name="userwalletgroup",
            name="callback",
            field=models.ForeignKey(
                blank=True,
                help_text="Provider's webhook endpoint for this user's notifications",
                limit_choices_to={"channel_type": "webhook"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_wallet_groups",
                to="app.notificationchannelendpoint",
            ),
        ),
        migrations.AddField(
            model_name="userwalletgroup",
            name="provider",
            field=models.ForeignKey(
                help_text="The provider/developer who manages this user's wallets",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_user_wallet_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwalletgroup",
            name="user",
            field=models.ForeignKey(
                help_text="The end-user whose wallets are managed in this group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_wallet_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwalletgroup",
            name="wallet_group",
            field=models.ForeignKey(
                help_text="The provider's WalletGroup containing these wallets",
                limit_choices_to={"group_type": "wallet"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_wallet_memberships",
                to="app.genericgroup",
            ),
        ),
        migrations.AddField(
            model_name="defaultnetworkalert",
            name="alert_template",
            field=models.OneToOneField(
                help_text="The fallback AlertTemplate for 'All Transactions' alerts",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_network_alert",
                to="app.alerttemplate",
            ),
        ),
        migrations.AddField(
            model_name="defaultnetworkalert",
            name="chain",
            field=models.ForeignKey(
                help_text="The blockchain chain (e.g., Ethereum, Solana)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_alerts",
                to="blockchain.chain",
            ),
        ),
        migrations.AddIndex(
            model_name="userwalletgroup",
            index=models.Index(
                fields=["user", "is_active"], name="user_wallet_user_id_a1a109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userwalletgroup",
            index=models.Index(
                fields=["wallet_group", "is_active"],
                name="user_wallet_wallet__614e59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userwalletgroup",
            index=models.Index(
                fields=["provider", "is_active"], name="user_wallet_provide_5803a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userwalletgroup",
            index=models.Index(
                fields=["created_at"], name="user_wallet_created_ae0f68_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userwalletgroup",
            unique_together={("user", "wallet_group")},
        ),
        migrations.AddIndex(
            model_name="defaultnetworkalert",
            index=models.Index(
                fields=["chain", "subnet"], name="default_net_chain_i_1e61d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defaultnetworkalert",
            index=models.Index(
                fields=["enabled"], name="default_net_enabled_2539f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="defaultnetworkalert",
            unique_together={("chain", "subnet")},
        ),
    ]
