# Generated by Django 4.2.7 on 2025-12-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_add_group_and_alert_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerttemplate",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("nlp_generated", "NLP Generated"),
                    ("system", "System Default"),
                ],
                default="manual",
                help_text="How this template was created: manual, nlp_generated, or system",
                max_length=20,
            ),
        ),
    ]
