# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add semantic fingerprinting and scope fields to AlertTemplate model.

    New fields:
    - semantic_fingerprint: 16-char hash for template deduplication
    - alert_type: Type of alert (wallet, network, token)
    - scope_chain: Chain identifier for scope constraint
    - scope_network: Network identifier (default mainnet)
    - similarity_group: 8-char hash for grouping similar templates

    New constraints:
    - unique_template_per_scope: Ensures unique fingerprint per chain+network
    """

    dependencies = [
        ("app", "0011_add_source_to_alerttemplate"),
    ]

    operations = [
        # Add semantic_fingerprint field
        migrations.AddField(
            model_name="alerttemplate",
            name="semantic_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="16-character semantic hash for template deduplication",
                max_length=16,
            ),
        ),
        # Add alert_type field
        migrations.AddField(
            model_name="alerttemplate",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Alert"),
                    ("network", "Network Alert"),
                    ("token", "Token Alert"),
                ],
                default="wallet",
                help_text="Type of alert: wallet (address-specific), network (chain-wide), or token (token-specific)",
                max_length=20,
            ),
        ),
        # Add scope_chain field
        migrations.AddField(
            model_name="alerttemplate",
            name="scope_chain",
            field=models.CharField(
                blank=True,
                help_text="Blockchain identifier (e.g., ethereum, polygon, solana)",
                max_length=50,
            ),
        ),
        # Add scope_network field
        migrations.AddField(
            model_name="alerttemplate",
            name="scope_network",
            field=models.CharField(
                default="mainnet",
                help_text="Network identifier (e.g., mainnet, testnet, goerli)",
                max_length=50,
            ),
        ),
        # Add similarity_group field
        migrations.AddField(
            model_name="alerttemplate",
            name="similarity_group",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="8-character hash for grouping similar templates",
                max_length=8,
            ),
        ),
        # Add composite index for alert_type + scope_chain
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["alert_type", "scope_chain"],
                name="app_alertte_alert_t_ba6d21_idx",
            ),
        ),
        # Add unique constraint for semantic_fingerprint + scope_chain + scope_network
        # Only enforced when semantic_fingerprint is not empty
        migrations.AddConstraint(
            model_name="alerttemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(semantic_fingerprint__gt=""),
                fields=["semantic_fingerprint", "scope_chain", "scope_network"],
                name="unique_template_per_scope",
            ),
        ),
    ]
