# Generated by Django 4.2.7 on 2025-12-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0012_add_semantic_fingerprint_and_scope_to_alerttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannelPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("webhook", "Webhook"),
                            ("websocket", "WebSocket"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        db_index=True,
                        help_text="Notification channel type",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether notifications are enabled for this channel",
                    ),
                ),
                (
                    "priority_filter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Priority levels to receive on this channel (e.g., ['critical', 'high']). Empty = all priorities.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Channel Preference",
                "verbose_name_plural": "Notification Channel Preferences",
                "db_table": "notification_channel_preferences",
            },
        ),
        migrations.RenameIndex(
            model_name="alerttemplate",
            new_name="alert_templ_alert_t_1ce104_idx",
            old_name="app_alertte_alert_t_ba6d21_idx",
        ),
        migrations.AlterField(
            model_name="alertinstance",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Alert"),
                    ("network", "Network Alert"),
                    ("token", "Token Alert"),
                    ("contract", "Contract Alert"),
                    ("nft", "NFT Alert"),
                ],
                default="wallet",
                help_text="Type of alert: wallet, network, or token - determines valid target types",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Alert"),
                    ("network", "Network Alert"),
                    ("token", "Token Alert"),
                ],
                default="wallet",
                help_text="Alert type determines scope constraints: wallet/network=single chain, token=multi-chain",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="scope_chain",
            field=models.CharField(
                blank=True,
                help_text="Chain scope (e.g., 'ethereum', 'solana'). Required for wallet/network alerts.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="scope_network",
            field=models.CharField(
                default="mainnet",
                help_text="Network scope (e.g., 'mainnet', 'testnet')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="semantic_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="16-character semantic hash for template deduplication based on structure",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="alerttemplate",
            name="similarity_group",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="8-character hash for similarity grouping (broader than fingerprint)",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="notificationchannelendpoint",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("telegram", "Telegram"),
                    ("slack", "Slack"),
                    ("webhook", "Webhook"),
                    ("sms", "SMS"),
                    ("discord", "Discord"),
                    ("whatsapp", "WhatsApp"),
                ],
                db_index=True,
                help_text="Notification channel type",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="alerttemplate",
            index=models.Index(
                fields=["similarity_group"], name="alert_templ_similar_f419c0_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationchannelpreferences",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannelpreferences",
            index=models.Index(
                fields=["user", "enabled"], name="notificatio_user_id_73be54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannelpreferences",
            index=models.Index(
                fields=["channel", "enabled"], name="notificatio_channel_0d214c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationchannelpreferences",
            unique_together={("user", "channel")},
        ),
    ]
