# Generated by Django migration
# Phase: AlertTemplateIR v1 Unified Schema
#
# This migration adds the new `spec` field for AlertTemplateIR v1 schema
# and marks old fields (spec_blueprint, variables) as deprecated by making
# them nullable. The validation_schema field is already nullable (default=dict).
#
# AlertTemplateIR v1 Schema Design:
# - Unified format optimized for Rust + Polars runtime
# - Two-stage evaluation: trigger pruning + batch conditions
# - Three datasource types: contract_call, ducklake, http_api
# - Structured expressions only (no raw code for security)
# - Variables embedded in spec with type/validation/UI hints

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_notification_channel_preferences'),
    ]

    operations = [
        # Add new unified spec field for AlertTemplateIR v1
        migrations.AddField(
            model_name='alerttemplate',
            name='spec',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="""AlertTemplateIR v1 unified schema for Rust+Polars runtime.
        {
            "version": "v1",
            "name": "High-Value Transfer Alert",
            "description": "Alert on large transfers exceeding threshold",

            "variables": [
                {
                    "id": "threshold",
                    "type": "decimal",
                    "label": "Transfer Threshold (USD)",
                    "description": "Minimum value to trigger alert",
                    "required": true,
                    "default": 100000,
                    "validation": {"min": 0, "max": 1000000000},
                    "ui": {"component": "currency_input", "unit": "USD"}
                }
            ],

            "trigger": {
                "chain_id": 1,
                "tx_type": {"primary": ["contract_call"], "subtypes": ["swap"]},
                "from": {"any_of": [], "labels": ["cex_hot"], "groups": [], "not": []},
                "to": {"any_of": [], "labels": [], "groups": ["{{wallet_group}}"], "not": []},
                "method_filter": {"selector_any_of": [], "name_any_of": ["swap"], "required": false}
            },

            "datasources": [
                {
                    "id": "ds_price",
                    "type": "http_api",
                    "config": {"endpoint": "coingecko_price", "params": ["token_id", "vs_currency"]},
                    "bindings": {"token_id": "$.tx.token_symbol", "vs_currency": "usd"},
                    "cache_ttl_secs": 60,
                    "timeout_ms": 1500
                }
            ],

            "enrichments": [
                {
                    "id": "en_value_usd",
                    "expr": {"op": "mul", "left": "$.tx.value_native", "right": "$.datasources.ds_price.price_usd"},
                    "output": "$.enrichment.value_usd"
                }
            ],

            "conditions": {
                "all": [{"op": "gt", "left": "$.enrichment.value_usd", "right": "{{threshold}}"}],
                "any": [],
                "not": []
            },

            "action": {"dedupe_key": "{{$.tx.hash}}", "cooldown_secs": 60},
            "warnings": []
        }"""
            ),
        ),

        # Deprecate spec_blueprint - make nullable for migration
        migrations.AlterField(
            model_name='alerttemplate',
            name='spec_blueprint',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="DEPRECATED: Use 'spec' field instead. Alert specification template with {{placeholders}}"
            ),
        ),

        # Deprecate variables - make nullable for migration
        migrations.AlterField(
            model_name='alerttemplate',
            name='variables',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="DEPRECATED: Use 'spec.variables' instead. Array of variable descriptors."
            ),
        ),

        # Update validation_schema help text to mark as deprecated
        migrations.AlterField(
            model_name='alerttemplate',
            name='validation_schema',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="DEPRECATED: Use 'spec' field instead. JSON schema for frontend form generation."
            ),
        ),
    ]
