# Generated by Django migration
# Phase: Remove legacy AlertTemplate fields (Approach A)
#
# Ekko now standardizes on AlertTemplate.spec (AlertTemplateIR v1) as the single
# persisted template representation used for execution and caching. The legacy
# fields `spec_blueprint`, `variables`, and `validation_schema` are removed.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_groupsubscription_target_key_and_constraints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alerttemplate",
            name="spec_blueprint",
        ),
        migrations.RemoveField(
            model_name="alerttemplate",
            name="variables",
        ),
        migrations.RemoveField(
            model_name="alerttemplate",
            name="validation_schema",
        ),
    ]

