# Generated by Django 6.0.1 on 2026-02-06 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_cleanup_alert_templates_table_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS developer_a_path_9b6b6f_idx RENAME TO developer_a_path_0969c0_idx;",
            reverse_sql="ALTER INDEX IF EXISTS developer_a_path_0969c0_idx RENAME TO developer_a_path_9b6b6f_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="apiendpoint",
                    new_name="developer_a_path_0969c0_idx",
                    old_name="developer_a_path_9b6b6f_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS developer_a_is_acti_2e4a30_idx RENAME TO developer_a_is_acti_8cd8a9_idx;",
            reverse_sql="ALTER INDEX IF EXISTS developer_a_is_acti_8cd8a9_idx RENAME TO developer_a_is_acti_2e4a30_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="apiendpoint",
                    new_name="developer_a_is_acti_8cd8a9_idx",
                    old_name="developer_a_is_acti_2e4a30_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS developer_a_user_id_5b0b75_idx RENAME TO developer_a_user_id_06d487_idx;",
            reverse_sql="ALTER INDEX IF EXISTS developer_a_user_id_06d487_idx RENAME TO developer_a_user_id_5b0b75_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="apikey",
                    new_name="developer_a_user_id_06d487_idx",
                    old_name="developer_a_user_id_5b0b75_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS developer_a_status_4bb3c5_idx RENAME TO developer_a_status_80837a_idx;",
            reverse_sql="ALTER INDEX IF EXISTS developer_a_status_80837a_idx RENAME TO developer_a_status_4bb3c5_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="apikey",
                    new_name="developer_a_status_80837a_idx",
                    old_name="developer_a_status_4bb3c5_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS developer_a_user_id_96b6a7_idx RENAME TO developer_a_user_id_01351e_idx;",
            reverse_sql="ALTER INDEX IF EXISTS developer_a_user_id_01351e_idx RENAME TO developer_a_user_id_96b6a7_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="apiusagerecord",
                    new_name="developer_a_user_id_01351e_idx",
                    old_name="developer_a_user_id_96b6a7_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_in_status_1e42e2_idx RENAME TO billing_inv_status_aefe38_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_inv_status_aefe38_idx RENAME TO billing_in_status_1e42e2_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billinginvoice",
                    new_name="billing_inv_status_aefe38_idx",
                    old_name="billing_in_status_1e42e2_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_in_billed_3f1f41_idx RENAME TO billing_inv_billed__3eb039_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_inv_billed__3eb039_idx RENAME TO billing_in_billed_3f1f41_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billinginvoice",
                    new_name="billing_inv_billed__3eb039_idx",
                    old_name="billing_in_billed_3f1f41_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_pl_slug_1b8b0c_idx RENAME TO billing_pla_slug_c2458d_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_pla_slug_c2458d_idx RENAME TO billing_pl_slug_1b8b0c_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billingplan",
                    new_name="billing_pla_slug_c2458d_idx",
                    old_name="billing_pl_slug_1b8b0c_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_pl_is_acti_0300ff_idx RENAME TO billing_pla_is_acti_57f551_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_pla_is_acti_57f551_idx RENAME TO billing_pl_is_acti_0300ff_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billingplan",
                    new_name="billing_pla_is_acti_57f551_idx",
                    old_name="billing_pl_is_acti_0300ff_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_su_user_id_4fdef4_idx RENAME TO billing_sub_user_id_c5f740_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_sub_user_id_c5f740_idx RENAME TO billing_su_user_id_4fdef4_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billingsubscription",
                    new_name="billing_sub_user_id_c5f740_idx",
                    old_name="billing_su_user_id_4fdef4_idx",
                ),
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS billing_su_status_56bcd9_idx RENAME TO billing_sub_status_9d3b01_idx;",
            reverse_sql="ALTER INDEX IF EXISTS billing_sub_status_9d3b01_idx RENAME TO billing_su_status_56bcd9_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name="billingsubscription",
                    new_name="billing_sub_status_9d3b01_idx",
                    old_name="billing_su_status_56bcd9_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alertinstance",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Alert"),
                    ("network", "Network Alert"),
                    ("protocol", "Protocol Alert"),
                    ("token", "Token Alert"),
                    ("contract", "Contract Alert"),
                    ("nft", "NFT Alert"),
                ],
                default="wallet",
                help_text="Type of alert: wallet, network, or token - determines valid target types",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alertinstance",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_EVENT", "Account Event"),
                    ("ASSET_EVENT", "Asset Event"),
                    ("CONTRACT_INTERACTION", "Contract Interaction"),
                    ("PROTOCOL_EVENT", "Protocol Event"),
                    ("DEFI_EVENT", "DeFi Event"),
                    ("ANOMALY_EVENT", "Anomaly Event"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alertinstance",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Pinned AlertTemplate identity for executable-backed alerts (vNext).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="app.alerttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="alertinstance",
            name="template_params",
            field=models.JSONField(
                blank=True,
                help_text="Variable bindings for this alert instance (used at evaluation time).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genericgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet Group"),
                    ("alert", "Alert Group"),
                    ("user", "User Group"),
                    ("network", "Network Group"),
                    ("protocol", "Protocol Group"),
                    ("token", "Token Group"),
                    ("contract", "Contract Group"),
                    ("nft", "NFT Collection Group"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS at2_created_by_idx ON alert_templates (created_by_id);",
            reverse_sql="DROP INDEX IF EXISTS at2_created_by_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="alerttemplate",
                    index=models.Index(fields=["created_by"], name="at2_created_by_idx"),
                ),
            ],
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS at2_visibility_idx ON alert_templates (is_public, is_verified);",
            reverse_sql="DROP INDEX IF EXISTS at2_visibility_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="alerttemplate",
                    index=models.Index(
                        fields=["is_public", "is_verified"], name="at2_visibility_idx"
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS at2_fingerprint_idx ON alert_templates (fingerprint);",
            reverse_sql="DROP INDEX IF EXISTS at2_fingerprint_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="alerttemplate",
                    index=models.Index(fields=["fingerprint"], name="at2_fingerprint_idx"),
                ),
            ],
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS atv_template_ver_idx ON alert_template_versions (template_id, template_version);",
            reverse_sql="DROP INDEX IF EXISTS atv_template_ver_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="alerttemplateversion",
                    index=models.Index(
                        fields=["template", "template_version"], name="atv_template_ver_idx"
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS atv_snapshot_hash_idx ON alert_template_versions (registry_snapshot_hash);",
            reverse_sql="DROP INDEX IF EXISTS atv_snapshot_hash_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name="alerttemplateversion",
                    index=models.Index(
                        fields=["registry_snapshot_hash"], name="atv_snapshot_hash_idx"
                    ),
                ),
            ],
        ),
    ]
